.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. feritcoin_qt test_feritcoin_qt
clean: FORCE
	$(MAKE) -C .. feritcoin_qt_clean test_feritcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_feritcoin_qt_check
feritcoin-qt feritcoin-qt.exe: FORCE
	 $(MAKE) -C .. feritcoin_qt
